# -*- coding: utf-8 -*-
"""Student performance analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jh9T0GDX9Ic5omv4xEpbGAEpSaz47HS_

Importing Libraries
"""

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from faker import Faker
fake=Faker()

!pip install faker
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from faker import Faker
fake=Faker()

np.random.seed(0)
names=[fake.name() for _ in range(250)]
data={
    "Student_ID":np.random.randint(1,500,250),
    "Names":names,
    "Gender":np.random.choice(["male","female"],250),
    "Department":np.random.choice(["CSE","IT","ECE"]),
    "Year":np.random.choice(["1st","2nd","3rd"]),
    "Maths":np.random.randint(10,100,250),
    "Science":np.random.randint(10,100,250),
    "English":np.random.randint(10,100,250),
    "Attendance":np.random.randint(50,100,250),
    "Internal Marks":np.random.randint(0,25,250)
}

df=pd.DataFrame(data)
df

print("\nChecking Missing Values:\n", df.isnull().sum())
print("\nData Types:\n", df.dtypes)

data['Total'] = data['Maths'] + data['Science'] + data['English']
data['Average'] = data['Total'] / 3
data['Total']
data['Average']

def grade(avg):
    if avg >= 75:
        return 'A'
    elif avg >= 60:
        return 'B'
    elif avg >= 50:
        return 'C'
    else:
        return 'Fail'

df['Grade'] = df['Average'].apply(grade)
df['Grade']

print("\nDescriptive Statistics:\n", df.describe())

top_students = df.sort_values(by='Average', ascending=False).head(10)
low_students = df[df['Grade'] == 'Fail']

print("\nTop 10 Students:\n", top_students[['Names', 'Average']])
print("\nFailed Students:\n", low_students[['Names', 'Average']])

dept_perf = df.groupby('Department')['Average'].mean()
print("\nDepartment-wise Performance:\n", dept_perf)

gender_perf = df.groupby('Gender')['Average'].mean()
print("\nGender-wise Performance:\n", gender_perf)

year_perf = df.groupby('Year')['Average'].mean()
print("\nYear-wise Performance:\n", year_perf)

plt.figure(figsize=(15,10))

plt.subplot(2,2,1)
dept_perf.plot(kind='bar')
plt.title('Department-wise Average Marks')

plt.subplot(2,2,2)
df['Gender'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title('Gender Distribution')

plt.subplot(2,2,3)
plt.hist(data['Average'], bins=10)
plt.title('Average Marks Distribution')

plt.subplot(2,2,4)
plt.scatter(data['Attendance'], data['Average'])
plt.title('Attendance vs Average Marks')
plt.xlabel('Attendance')
plt.ylabel('Average Marks')

plt.tight_layout()
plt.show()

plt.figure(figsize=(6,4))
sns.heatmap(df[['Maths','Science','English','Attendance','Internal Marks','Average']].corr(), annot=True)
plt.title("Correlation Matrix")
plt.show()

print("\n--- Insights ---")
print("1. Students with higher attendance tend to score better.")
print("2. Internal marks show positive relation with final performance.")
print("3. Department-wise variation exists in performance.")
print("4. Few students fall into fail category and need attention.")